/* AUTO-GENERATED by scripts/sync-videos.mjs — do not edit by hand.
   Run `npm run sync:videos` to refresh from the Drive folder.

   THIS FILE HOLDS NO URLS. It used to hold 204 of them — three absolute blob
   URLs per reel, each with a random per-upload suffix — which is why
   lib/reelOrder.ts keys display order on `id`: the id was the only field that
   survived a sync. The keys are ours and deterministic now (`addRandomSuffix`
   is off — see scripts/upload-blob.mjs), so what is stored here is the id and
   which variants exist, and the URLs are derived from lib/cdn.ts at import.
   Moving the library to a different store, or to R2 later, is then a change to
   one environment variable and nothing else.

   THE `Reel` SHAPE IS UNCHANGED, and deliberately so. Every consumer —
   LazyVideo, ReelWallV6, Work, Testimonials, the lib/v2..v8 data modules — still receives
   `{ id, src, hq, poster }` with the same field names and the same nullability.
   The derivation happens here, below the export, so none of them had to learn
   where the library moved to. */

import { cdnUrl } from "./cdn";

export type Reel = {
  /** Stable slug taken from the Drive filename — see slugify() in
      scripts/sync-videos.mjs. lib/reelOrder.ts keys the display order on this,
      so changing one reorders both walls. */
  id: string;
  /** Small, silent tile cut — what the walls autoplay. */
  src: string;
  /** Larger cut with audio, for the lightbox. Null when the sync could not
      produce one, in which case callers fall back to src. */
  hq: string | null;
  poster: string | null;
};

/* What the sync actually found on disk. Flags rather than URLs: whether a
   variant EXISTS is a fact about the library, where it is served from is not. */
type Entry = { id: string; hq: boolean; poster: boolean };

const ENTRIES: Entry[] = [
  { id: "0616", hq: true, poster: true },
  { id: "ai-podcast", hq: true, poster: true },
  { id: "ai-ugc-gym-perfume-ad", hq: true, poster: true },
  { id: "boyfriend-angle-ai", hq: true, poster: true },
  { id: "doctor-and-specialist-podcast-viral-ai-ugc", hq: true, poster: true },
  { id: "doctor-in-office-ai-ugc-health-product", hq: true, poster: true },
  { id: "expert-doctor-review-ai-ugc", hq: true, poster: true },
  { id: "health-product-ai-ugc-1", hq: true, poster: true },
  { id: "hoodie-ad-podcast-style", hq: true, poster: true },
  { id: "live-stage-doctor-ai-ugc-health-product", hq: true, poster: true },
  { id: "perfume-blind-test-1", hq: true, poster: true },
  { id: "v2702", hq: true, poster: true },
  { id: "v2870", hq: true, poster: true },
  { id: "v2934", hq: true, poster: true },
  { id: "v3057", hq: true, poster: true },
  { id: "v3183", hq: true, poster: true },
  { id: "v3189", hq: true, poster: true },
  { id: "v3293", hq: true, poster: true },
  { id: "v3317", hq: true, poster: true },
  { id: "v3445", hq: true, poster: true },
  { id: "v3512", hq: true, poster: true },
  { id: "v3532", hq: true, poster: true },
  { id: "v3558", hq: true, poster: true },
  { id: "v3579", hq: true, poster: true },
  { id: "v3583", hq: true, poster: true },
  { id: "v3636", hq: true, poster: true },
  { id: "v3666", hq: true, poster: true },
  { id: "v3683", hq: true, poster: true },
  { id: "v3752", hq: true, poster: true },
  { id: "v3885", hq: true, poster: true },
  { id: "v4134", hq: true, poster: true },
  { id: "v4140", hq: true, poster: true },
  { id: "v4147", hq: true, poster: true },
  { id: "v4149", hq: true, poster: true },
  { id: "v4493", hq: true, poster: true },
  { id: "v4508", hq: true, poster: true },
  { id: "v4824", hq: true, poster: true },
  { id: "v4872", hq: true, poster: true },
  { id: "v5304", hq: true, poster: true },
];

export const reelVideos: Reel[] = ENTRIES.map(({ id, hq, poster }) => ({
  id,
  src: cdnUrl(`reels/${id}.mp4`),
  hq: hq ? cdnUrl(`reels/${id}.hq.mp4`) : null,
  poster: poster ? cdnUrl(`reels/${id}.webp`) : null,
}));
