/* THE ONE PLACE lib/reels.generated.ts IS WRITTEN.

   Kept out of sync-videos.mjs so that regenerating the manifest and
   transcoding 68 clips are separate operations. The sync calls this at the end
   of a run; nothing else should write that file.

   DETERMINISTIC BY CONSTRUCTION. Same ids in, byte-identical file out — the
   entries are sorted, the shape is fixed, and there is no timestamp, no run id
   and no counter anywhere in the output. That is what makes `npm run
   sync:videos` safe to run twice: the second run produces no diff. */

import fs from "node:fs";
import path from "node:path";

/** Repo-root-relative path of the file this module owns. */
export const GENERATED_PATH = "lib/reels.generated.ts";

/* ASCII sort on the id, which is what the old pipeline emitted and therefore
   what lib/reelOrder.ts has always been fed. It matters more than it looks:
   spreadReels() walks this array to build its subject groups, so the ARRAY
   ORDER is an input to the wall order, not just a cosmetic detail. Sorting on
   anything else here silently reshuffles both walls. */
export function sortEntries(entries) {
  return [...entries].sort((a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0));
}

const HEADER = `/* AUTO-GENERATED by scripts/sync-videos.mjs — do not edit by hand.
   Run \`npm run sync:videos\` to refresh from the Drive folder.

   THIS FILE HOLDS NO URLS. It used to hold 204 of them — three absolute blob
   URLs per reel, each with a random per-upload suffix — which is why
   lib/reelOrder.ts keys display order on \`id\`: the id was the only field that
   survived a sync. The keys are ours and deterministic now (\`addRandomSuffix\`
   is off — see scripts/upload-blob.mjs), so what is stored here is the id and
   which variants exist, and the URLs are derived from lib/cdn.ts at import.
   Moving the library to a different store, or to R2 later, is then a change to
   one environment variable and nothing else.

   THE \`Reel\` SHAPE IS UNCHANGED, and deliberately so. Every consumer —
   LazyVideo, ReelWallV6, Work, Testimonials, the lib/v2..v8 data modules — still receives
   \`{ id, src, hq, poster }\` with the same field names and the same nullability.
   The derivation happens here, below the export, so none of them had to learn
   where the library moved to. */

import { cdnUrl } from "./cdn";

export type Reel = {
  /** Stable slug taken from the Drive filename — see slugify() in
      scripts/sync-videos.mjs. lib/reelOrder.ts keys the display order on this,
      so changing one reorders both walls. */
  id: string;
  /** Small, silent tile cut — what the walls autoplay. */
  src: string;
  /** Larger cut with audio, for the lightbox. Null when the sync could not
      produce one, in which case callers fall back to src. */
  hq: string | null;
  poster: string | null;
};

/* What the sync actually found on disk. Flags rather than URLs: whether a
   variant EXISTS is a fact about the library, where it is served from is not. */
type Entry = { id: string; hq: boolean; poster: boolean };

const ENTRIES: Entry[] = [
`;

const FOOTER = `];

export const reelVideos: Reel[] = ENTRIES.map(({ id, hq, poster }) => ({
  id,
  src: cdnUrl(\`reels/\${id}.mp4\`),
  hq: hq ? cdnUrl(\`reels/\${id}.hq.mp4\`) : null,
  poster: poster ? cdnUrl(\`reels/\${id}.webp\`) : null,
}));
`;

/**
 * Render the manifest. Returns the file contents; does not write.
 * @param entries [{ id, hq: boolean, poster: boolean }]
 */
export function renderReels(entries) {
  const rows = sortEntries(entries)
    .map((e) => `  { id: ${JSON.stringify(e.id)}, hq: ${!!e.hq}, poster: ${!!e.poster} },`)
    .join("\n");
  return `${HEADER}${rows}\n${FOOTER}`;
}

/**
 * Write the manifest if it differs. Returns true when the file changed, which
 * is what lets a second sync run report "no change" rather than touching mtime.
 */
export function writeReels(entries, repoRoot = process.cwd()) {
  const target = path.join(repoRoot, GENERATED_PATH);
  const next = renderReels(entries);
  const current = fs.existsSync(target) ? fs.readFileSync(target, "utf8") : null;
  if (current === next) return false;
  fs.writeFileSync(target, next);
  return true;
}
